language: python
python:
- 3.6.5
install: pip install -r requirements.txt
script: coverage run -m unittest test/utilstest.py
after_success: codecov
before_install:
- openssl aes-256-cbc -K $encrypted_90e1fbe2129f_key -iv $encrypted_90e1fbe2129f_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
