language: python
python:
- 3.5.2
before_install:
- openssl aes-256-cbc -K $encrypted_c47483315b1f_key -iv $encrypted_c47483315b1f_iv
  -in captains.json.enc -out captains.json -d
install: pip install -r requirements.txt
script: python -m unittest test/utilstest.py
after_success: codecov
