language: python
python:
- 3.5.2
install: pip install -r requirements.txt
script: coverage run -m unittest test/utilstest.py
after_success: codecov
before_install:
- openssl aes-256-cbc -K $encrypted_90e1fbe2129f_key -iv $encrypted_90e1fbe2129f_iv
  -in client_secret.json.enc -out client_secret.json -d
- openssl aes-256-cbc -K $encrypted_90e1fbe2129f_key -iv $encrypted_90e1fbe2129f_iv
  -in captains.json.enc -out captains.json -d
